name = Base Site
description = HTML Base para el site
category = Jarula Custom
preview = preview.png
template = base-site-layout
admin css = ../../../unsemantic_theme/unsemantic-master/assets/stylesheets/unsemantic-grid-responsive.css

; Regions

; ---- Header
regions[header_logo]       = Logo
regions[header_search]       = Search
regions[header_menu]       = Menu

; ---- Main
regions[main_top]      = Main Top
regions[main]      = Main

; ---- Footer
regions[footer_menu]      = Menu
regions[footer_copyright]      = Copyright
