<?php
/**
 * @file
 * Code for the Jarula Widgets.
 */

function jarula_widgets_form_alter(&$form, &$form_state, $form_id) {

	if (isset($form['#entity_type']) && $form['#entity_type'] == 'fieldable_panels_pane') {
		$form['link'] = NULL;
		$form['view_mode'] = NULL;
	}

}

function jarula_widgets_ctools_plugin_directory($owner, $plugin_type) {

	if (($owner == 'ctools' && $plugin_type == 'content_types') || ($owner == 'panels' && $plugin_type == "layouts")) {
		return "plugins/$plugin_type";
	}elseif ($owner == 'vud') {
  		return "plugins/$plugin_type";
	}
}

function jarula_widgets_entity_info_alter(&$entity_info) {

	$entity_info['fieldable_panels_pane']['bundles']['widget_image'] = array(
			'label' => 'Widget Image',
			'category' => 'Jarula Widgets',
			'pane top level' => TRUE, // set to true to make this show as a top level icon
			//'pane icon' => '/path/to/custom/icon/for/this/pane.png',
			'admin' => array(
			  'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
			  'bundle argument' => 4,
			  // Note that this has all _ replaced with - from the bundle name.
			  'real path' => 'admin/structure/fieldable-panels-panes/manage/widget_image',
			  'access arguments' => array('Administer content'),
		),
	);

        $entity_info['fieldable_panels_pane']['bundles']['widget_text'] = array(
                        'label' => 'Widget Texto',
                        'category' => 'Jarula Widgets',
                        'pane top level' => TRUE, // set to true to make this show as a top level icon
                        //'pane icon' => '/path/to/custom/icon/for/this/pane.png',
                        'admin' => array(
                          'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
                          'bundle argument' => 4,
                          // Note that this has all _ replaced with - from the bundle name.
                          'real path' => 'admin/structure/fieldable-panels-panes/manage/widget_text',
                          'access arguments' => array('Administer content'),
                ),
        );


}

function jarula_widgets_preprocess_panels_pane(&$vars) {

	$entity = &$vars['content'];
	$vars['title'] = '';
	$images = array();

	if ( isset($entity['#bundle']) && $entity['#entity_type'] == 'fieldable_panels_pane') {

		switch ($entity['#bundle']) {

			case 'widget_image':
                                
				$lightbox = $entity['field_lightbox'][0]['#markup'];

				foreach($entity['field_image']['#items'] as $key => $image) {
					$imageRendered = theme( 'image_style', array('style_name' => 'small_wide', 'path' => $image['uri'], 'alt' => $image['alt'], 'title' => $image['title']));
					if(!empty($lightbox)){
						$imageRendered = l($imageRendered, file_create_url($image['uri']), array('html' => 'true', 'attributes' => array('title' => $image['title'], 'alt' => $image['alt'], 'class' => 'colorbox-load', 'rel' => 'gallery')));
					};

					$images[] = $imageRendered;

				}

				$vars['content'] = theme('widget_image', array('widget_image' => $images));

			break;

			case 'widget_text':

		                $wrapper = $entity['field_wrapper'][0]['#markup'];

                		$arrayText = array_keys($entity['field_text']);

		                foreach ($arrayText as $item){
                		        if(is_numeric($item)){
                                		$element = $entity['field_text'][$item];
		                                foreach($element['entity']['field_collection_item'] as $fieldCollection){
		                                        (isset($fieldCollection['title_field'])) ? $title = '<h2>' . $fieldCollection['title_field'][0]['#markup'] . '</h2>' : $title = '';
		                                        (isset($fieldCollection['field_description'])) ? $description = '<p>' . $fieldCollection['field_description'][0]['#markup'] . '</p>' : $description = '';
		                                        $texts[] = array(
		                                                'title' => $title,
		                                                'description' => $description,
                		                        );
                                		}
		                        }
		                }
	
        		        $widget_text = array('wrapper' => $wrapper, 'texts' => $texts);

		                $vars['content'] = theme('widget_text', array('widget_text' => $widget_text));

			break;

        	}
	}
}

function jarula_widgets_theme() {

	return array(
		'widget_image' => array(
			'template' => 'widget-image',
			'path' => drupal_get_path('module', 'jarula_widgets') . '/templates',
		),
                'widget_text' => array(
                        'template' => 'widget-text',
                        'path' => drupal_get_path('module', 'jarula_widgets') . '/templates',
                ),
        );

}
