name = Node
description = Nodes structure
category = Jarula Custom
preview = preview.png
template = node-layout
admin css = ../../../unsemantic_theme/unsemantic-master/assets/stylesheets/unsemantic-grid-responsive.css

; Regions

regions[info]      = Info
regions[map]       = Map
regions[slider]    = Slider
regions[planes]    = Planes
regions[features]  = Features
regions[more]      = More
regions[contact]   = Contact
regions[related]   = Related
