name = One Top and Three Columns
description = t("One Top and Three Columns")
category = Jarula Custom
preview = preview.png
template = top-three-columns-layout
admin css = ../../../unsemantic_theme/unsemantic-master/assets/stylesheets/unsemantic-grid-responsive.css

; Regions

; ---- Top
regions[top]         = Top

; ---- Columns
regions[left]        = Left
regions[center]      = Center
regions[right]       = Right

