name = Unsemantic
description = Unsemantic como motor responsive
preview = preview.png
template = unsemantic-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[content]        = Content
regions[help]           = Help
regions[footer]         = Footer
regions[footer_logo]    = Footer Logo
regions[footer_menu]    = Footer Menu

; Stylesheets
stylesheets[all][] = css/layouts/unsemantic/unsemantic.layout.css
stylesheets[all][] = css/general/base.css
stylesheets[all][] = css/general/reset.css
stylesheets[all][] = css/general/system.css

; Scripts
scripts[] = layouts/off-canvas/assets/unsemantic.js
