<?php
/**
 * @file
 * Code for the Jarola Widgets.
 */

function jarola_widgets_form_alter(&$form, &$form_state, $form_id) {

	if (isset($form['#entity_type']) && $form['#entity_type'] == 'fieldable_panels_pane') {
		$form['link'] = NULL;
		$form['view_mode'] = NULL;
	}

}

drupal_add_css(drupal_get_path('module', 'jarola_widgets') . '/css/jarola_widgets.css');

function jarola_widgets_ctools_plugin_directory($owner, $plugin_type) {

  if (($owner == 'ctools' && $plugin_type == 'content_types') || ($owner == 'panels' && $plugin_type == "layouts")) {
    return "plugins/$plugin_type";
  }elseif ($owner == 'vud') {
  	return "plugins/$plugin_type";
  }
}

function jarola_widgets_entity_info_alter(&$entity_info) {

/* ---->CONSTRUCTION<----

	$entity_info['fieldable_panels_pane']['bundles']['{bundle_machine_name}'] = array(
			'label' => '{Bundle Name}',
			'category' => 'Jarola Widgets',
			'pane top level' => FALSE, // set to true to make this show as a top level icon
			//'pane icon' => '/path/to/custom/icon/for/this/pane.png',
			'admin' => array(
			  'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
			  'bundle argument' => 4,
			  // Note that this has all _ replaced with - from the bundle name.
			  'real path' => 'admin/structure/fieldable-panels-panes/manage/{bundle_machine_name}',
			  'access arguments' => array('Administer content'),
		),
	);


/* ---->EXAMPLE<----
	$entity_info['fieldable_panels_pane']['bundles']['bundle_test'] = array(
			'label' => 'Bundle Test',
			'category' => 'Jarola Widgets',
			'pane top level' => FALSE, // set to true to make this show as a top level icon
			//'pane icon' => '/path/to/custom/icon/for/this/pane.png',
			'admin' => array(
			  'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
			  'bundle argument' => 4,
			  // Note that this has all _ replaced with - from the bundle name.
			  'real path' => 'admin/structure/fieldable-panels-panes/manage/bundle_test',
			  'access arguments' => array('Administer content'),
		),
	);
*/
}

function jarola_widgets_preprocess_panels_pane(&$vars) {

	$entity = &$vars['content'];
	$vars['title'] = '';

	if ( isset($entity['#bundle']) && $entity['#entity_type'] == 'fieldable_panels_pane' ) {

		switch ($entity['#bundle']) {

/* ---->CONSTRUCTION<----
			case '{bundle_machine_name}':

				MAGIC HERE...

				$vars['content'] = theme('jarola_widgets_{bundle_machine_name}', array('{system_name}' => {bundle_array}));

			break;

/* ---->EXAMPLE<----
			case 'bundle_test':

				$title = $entity['field_long']['#object']->title_field['und'][0]['safe_value'];
				$description = $entity['field_long']['#object']->field_long['und'][0]['safe_value'];

				$bundle_test_array = array($title, $description);

				$vars['content'] = theme('jarola_widgets_bundle_test', array('bundle_test' => $bundle_test_array));

			break;
*/

	}
}

function jarola_widgets_theme() {

	return array(
/* ---->CONSTRUCTION<----
		'jarola_widgets_{bundle_machine_name}' => array(
			'template' => 'jarola-widgets-{bundle_template_name}',
			'path' => drupal_get_path('module', 'jarola_widgets') . '/templates',
		)

/* ---->EXAMPLE<----
		'jarola_widgets_bundle_test' => array(
			'template' => 'jarola-widgets-bundle-test',
			'path' => drupal_get_path('module', 'jarola_widgets') . '/templates',
		)
*/
	);
}